checks fixes

diff --git a/.github/workflows/frontend_checks.yaml b/.github/workflows/frontend_checks.yaml
--- a/.github/workflows/frontend_checks.yaml
+++ b/.github/workflows/frontend_checks.yaml
@@ -1,25 +1,32 @@
-name: Continuous Integration
+name: Lint and Test on Pull Request Frontend
 
-# This action works with pull requests and pushes
-on:
-  pull_request:
-  push:
-    branches:
-      - main
+on: pull_request
 
 jobs:
-  prettier:
+  frontend-commit-checks:
     runs-on: ubuntu-latest
-
+    name: Checks before commit
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Prettify code
-        uses: creyD/prettier_action@v4.3
+      - name: Read .nvmrc
+        run: echo "##[set-output name=NVMRC;]$(cat client/.nvmrc)"
+        id: nvm
+      - name: Use Node.js (.nvmrc)
+        uses: actions/setup-node@v4
         with:
-          prettier_options: --write --ignore-unknown
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          node-version: "${{ steps.nvm.outputs.NVMRC }}"
+      - name: Install dependencies
+        run: yarn
+      - name: Run lint
+        run: yarn lint --quiet
+      - name: Run Tests
+        run: yarn test
+      - name: Check for changes
+        run: git diff --exit-code
+      - name: Comment on PR if lint fails
+        if: ${{ failure() }}
+        run: |
+          echo "Lint checks failed. Please review and fix the issues."
+          exit 1
